theme: osuny
_merge: deep
params:
  events:
    sitemap:
      ignore: true
  exhibitions:
    sitemap:
      ignore: true
  jobs:
    sitemap:
      ignore: true
  organizations:
    sitemap:
      ignore: true
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/main-logo.png'
    footer: '/assets/images/white-logo.png'
  home:
    head:
      title: site