[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/mallory-carlu-geremie/index.html"
to = "/personnes/mallory-carlu-geremie/"

[[redirects]]
from = "/projets/2021-relief/index.html"
to = "/projets/2024-relief/"

[[redirects]]
from = "/clement-chabre/index.html"
to = "/personnes/clement-chabre/"

[[redirects]]
from = "/notre-projet-collaboratif/index.html"
to = "/projet-collaboratif/"

[[redirects]]
from = "/projets/2026-ville-de-givors/index.html"
to = "/projets/2025-ville-de-givors/"

[[redirects]]
from = "/sylvain-couture/index.html"
to = "/personnes/sylvain-couture/"

[[redirects]]
from = "/actualites/2026-03-04-actualite-3/index.html"
to = "/actualites/2026-03-03-actualite-3/"

[[redirects]]
from = "/actualites/2026-03-17-actualite-3/index.html"
to = "/actualites/2026-03-03-actualite-3/"

[[redirects]]
from = "/nos-champs-dintervention/index.html"
to = "/champs-dintervention/"

[[redirects]]
from = "/projets/2022-ecole-ecologica/index.html"
to = "/projets/2025-ecole-ecologica/"

[[redirects]]
from = "/projets/2026-ecole-ecologica/index.html"
to = "/projets/2025-ecole-ecologica/"

[[redirects]]
from = "/projets/2024-ville-de-givors/index.html"
to = "/projets/2025-ville-de-givors/"

